# Generated by Django 4.0 on 2021-12-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('1', 'Algorithm'), ('2', 'Data Structures'), ('3', 'Dynamic Programming'), ('4', 'Mathematics'), ('5', 'Implementation'), ('6', 'String'), ('7', 'Searching and Sortings'), ('8', 'Graph'), ('9', 'Geometry'), ('10', 'Miscellaneous'), ('11', 'Live Contest')], default='Live Contest', max_length=255),
        ),
    ]
